spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.106
    port: 6379
server:
  context-path: /sell


wechat:
  mpAppId: wx3336091da1d33f27
  mpAppSecret: b26c4d35e1cfb7d3b38ecbe10ea670de
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://swf.natapp1.cc/sell/pay/notify
  templateId:
      orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ


projectUrl:
  wechatMpAuthorize: http://swf.natapp1.cc
  wechatOpenAuthorize: http://swf.natapp1.cc
  sell: http://swf.natapp1.cc





